### ISSUE TITLE
Roadmap: Icons for clinical applications

### ISSUE THREAD

**Issue by henrykrumb** [ai-health-care/med-ui-icons#1]
- [ ] Icons representing the [anatomical planes](https://en.wikipedia.org/wiki/Anatomical_terms_of_location#Planes)
- [ ] Icons resembling different organs (liver, kidney, heart, vessels,...)
- [ ] Icons for different imaging modalities (X-ray, MRI, CT, U/S)
