### ISSUE TITLE
Roadmap: Additional symbols

### ISSUE THREAD

**Issue by henrykrumb** [ai-health-care/med-ui-icons#3]
- [ ] "Info" (exclamation mark) and "Help" (question mark) symbols
- [ ] Speech bubble
- [ ] Basic Emoticons: Excited, Happy, Neutral, Sad, Devastated
- [ ] Human of male/female phenotype, child
